name: Build Android APK and Deploy Web

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.32.5'
        channel: 'stable'
        cache: true
    
    - name: Get dependencies
      run: flutter pub get
    
    - name: Analyze code
      run: flutter analyze --no-fatal-infos
    
    - name: Run tests
      run: flutter test
    
    - name: Build APK
      run: flutter build apk --release
    
    - name: Build Web
      run: flutter build web --release --base-href "/recipe-manager/"
    
    - name: Copy 404.html for GitHub Pages SPA routing
      run: cp build/web/index.html build/web/404.html
    
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: recipe-manager-apk
        path: build/app/outputs/flutter-apk/app-release.apk
    
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/web
    
    - name: Create Release
      if: github.ref == 'refs/heads/main'
      run: |
        gh release create v${{ github.run_number }} \
          --title "Release v${{ github.run_number }}" \
          --notes "Auto-generated release with APK

        ## Installation
        1. Download the APK file below
        2. Enable 'Install from unknown sources' on your Android device
        3. Install the APK" \
          build/app/outputs/flutter-apk/app-release.apk
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}